/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JFrame;

/**
 *
 * @author Alvaro
 */
public class Enfermedad extends javax.swing.JFrame {

    private JFrame frameAnterior;
    public Enfermedad(JFrame frameAnterior) {
        initComponents();
        this.frameAnterior=frameAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelContagiosa = new javax.swing.JLabel();
        labelEnfermedades = new javax.swing.JLabel();
        labelDosis = new javax.swing.JLabel();
        labelNombreEnfermedad = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEnfermedaades = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTratamiento = new javax.swing.JList<>();
        CheckBoxSi = new javax.swing.JCheckBox();
        labelTratamiento = new javax.swing.JLabel();
        CheckBoxNo = new javax.swing.JCheckBox();
        labelDos = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        labelNum = new javax.swing.JLabel();
        labelNumDiaria = new javax.swing.JLabel();
        listaInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelContagiosa.setText("Contagiosa:");

        labelEnfermedades.setText("Enfermedades relacionadas:");

        labelDosis.setText("Dosis:");

        labelNombreEnfermedad.setText("Nombre enfermedad");

        listaEnfermedaades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaEnfermedaades);

        listaTratamiento.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaTratamiento);

        CheckBoxSi.setSelected(true);
        CheckBoxSi.setText("Si");
        CheckBoxSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxSiActionPerformed(evt);
            }
        });

        labelTratamiento.setText("Tratamiento");

        CheckBoxNo.setText("No");

        labelDos.setText("Dosis");

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        labelNum.setText("Numero de dosis diaria");

        labelNumDiaria.setText("Numero de dosis diarias:");

        listaInfo.setText("Información del tratamiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTratamiento)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelEnfermedades)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelDosis)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelDos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelNumDiaria)
                                        .addComponent(labelContagiosa))
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(CheckBoxSi)
                                            .addGap(18, 18, 18)
                                            .addComponent(CheckBoxNo))
                                        .addComponent(labelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(75, 75, 75)))
                    .addComponent(listaInfo))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(labelNombreEnfermedad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVolver)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelNombreEnfermedad)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTratamiento)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listaInfo)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDosis)
                            .addComponent(labelDos))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNumDiaria)
                            .addComponent(labelNum))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelContagiosa)
                            .addComponent(CheckBoxSi)
                            .addComponent(CheckBoxNo))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(labelEnfermedades)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(botonVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxSiActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.setVisible(false);
        frameAnterior.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxNo;
    private javax.swing.JCheckBox CheckBoxSi;
    private javax.swing.JButton botonVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelContagiosa;
    private javax.swing.JLabel labelDos;
    private javax.swing.JLabel labelDosis;
    private javax.swing.JLabel labelEnfermedades;
    private javax.swing.JLabel labelNombreEnfermedad;
    private javax.swing.JLabel labelNum;
    private javax.swing.JLabel labelNumDiaria;
    private javax.swing.JLabel labelTratamiento;
    private javax.swing.JList<String> listaEnfermedaades;
    private javax.swing.JLabel listaInfo;
    private javax.swing.JList<String> listaTratamiento;
    // End of variables declaration//GEN-END:variables
}
