/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Enfermera;
import controlador.ListaEnfermeras;
import controlador.ListaMedicos;
import controlador.Medico;

/**
 *
 * @author Alvaro
 */
public class Login extends javax.swing.JFrame {

    private MenuMedico medico;
    private VentanaEnfermera enfermera;
    private static ListaEnfermeras listaEnfermeras= new ListaEnfermeras();
    private static ListaMedicos listaMedicos= new ListaMedicos();
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLogin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        textFieldIdentificador = new javax.swing.JTextField();
        jTextFieldCont = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        buttonEntrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("HOSPITAL");

        textFieldIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdentificadorActionPerformed(evt);
            }
        });

        jTextFieldCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonEntrar.setText("Entrar");
        buttonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEntrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Identificador");

        jLabel3.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldCont, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(buttonEntrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCont, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(buttonEntrar)
                .addGap(84, 84, 84)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldIdentificadorActionPerformed

    private void jTextFieldContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEntrarActionPerformed

        int ident = Integer.parseInt(textFieldIdentificador.getText());
        String cont = jTextFieldCont.getText();
        Medico aux = new Medico(ident,cont);
        Enfermera auxE = new Enfermera(ident,cont);
        
        
        if (listaMedicos.contains(aux))
        {
            medico = new MenuMedico(this);
            this.setVisible(false);
            medico.setVisible(true);
        }
        else if (listaEnfermeras.contains(auxE))
        {
            enfermera = new VentanaEnfermera(this);
            this.setVisible(false);
            enfermera.setVisible(true);
        }
        
        else System.out.println("Error en identificador o contraseña");
    }//GEN-LAST:event_buttonEntrarActionPerformed

    private void buttonEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnfermeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEnfermeraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Login login = new Login();
        login.setVisible(true);
        
        Medico medico = new Medico(0,"cont0");
        Enfermera enfermera = new Enfermera(1,"cont1");
        
        listaMedicos.addMedico(medico);
        listaEnfermeras.addEnfermera(enfermera);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEntrar;
    private javax.swing.ButtonGroup buttonGroupLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldCont;
    private javax.swing.JTextField textFieldIdentificador;
    // End of variables declaration//GEN-END:variables
}
