/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Enfermo;
import controlador.ListaEnfermos;
import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;

/**
 *
 * @author Alvaro
 */
public class VerPacientes extends javax.swing.JFrame {

    private ListaEnfermos listaEnfermos;
    private JFrame frameAnterior;
    public VerPacientes(JFrame frameAnterior) {
        initComponents();
        this.frameAnterior=frameAnterior;
    }

    
    /**
     *
     */
    public void updateListActividades() {

        DefaultListModel listModelPacientes = new DefaultListModel();
        for (Object item : listaEnfermos.consultarPacientes()) {
            listModelPacientes.addElement(item);
        }

        listaPacientes.setModel(listModelPacientes);
        listaPacientes.setCellRenderer(new NombrePacienteCellRenderer());
    }
    
    /**
     *
     */
    public class NombrePacienteCellRenderer extends DefaultListCellRenderer {

        public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {

            JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            label.setText(value.toString());
            return label;
        }
    }
    
    
    public void limpiarDetallesPaciente() {
        labelNom.setText("");
        labelApe.setText("");
        labelHab.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelApellidos = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        labelHab = new javax.swing.JLabel();
        labelHabitacion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEnfermedades = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPacientes = new javax.swing.JList<>();
        labelPacientes = new javax.swing.JLabel();
        labelInfo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        labelApe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelApellidos.setText("Apellidos:");

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        labelHab.setText("Habitacion");

        labelHabitacion.setText("Habitacion:");

        listaEnfermedades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Enfermedad 1", "Enfermedad 2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaEnfermedades);

        listaPacientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Paciente 1", "Paciente 2", "Paciente 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaPacientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPacientesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaPacientes);

        labelPacientes.setText("Lista de pacientes");

        labelInfo.setText("Información de paciente");

        labelNombre.setText("Nombre:");

        labelNom.setText("Nombre");

        labelApe.setText("Apellidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPacientes)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(botonVolver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelInfo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelNombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelApellidos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelApe, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelHabitacion)
                                    .addGap(18, 18, 18)
                                    .addComponent(labelHab, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(190, 190, 190))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPacientes)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(botonVolver)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInfo)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(labelNom))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidos)
                    .addComponent(labelApe))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHabitacion)
                    .addComponent(labelHab))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.setVisible(false);
        frameAnterior.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed

    private void listaPacientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPacientesValueChanged
        // TODO add your handling code here:
        //Si se selecciona un paciente valido
        if (!listaPacientes.getValueIsAdjusting() && listaPacientes.getSelectedValue() != null) {
            //Limpiar campos del paciente actual
            limpiarDetallesPaciente();
            //Rellenar campos del paciente actual
            Object paciente = listaPacientes.getSelectedValue();
            Enfermo detallesPaciente = listaEnfermos.consultarDetallesEnfermo(paciente);
            labelNom.setText(detallesPaciente.getIdentificador());
            labelApe.setText(detallesPaciente.getApellidos());
            labelHab.setText(detallesPaciente.getHabitacion());
           
        }
    }//GEN-LAST:event_listaPacientesValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolver;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelApe;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelHab;
    private javax.swing.JLabel labelHabitacion;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPacientes;
    private javax.swing.JList<String> listaEnfermedades;
    private javax.swing.JList<String> listaPacientes;
    // End of variables declaration//GEN-END:variables
}
